train_model:
  dataset_name: "roneneldan/TinyStories"
  sample_size: 1000
  test_size: 0.2
  embedding: "glove.6B.50d.txt"
  model_type: "random_forest"
  model_params:
    mode: "regression"
    context_size: 97
    alpha: 0.47
  nested_params:
    # "cpp_alpha": 0.28343478986616377,
    # "max_depth": 10,
    # "min_samples_split": 8,
    # "max_depth": 13,
    # "min_samples_leaf": 12,
    # learning_rate: 0.002,
    # n_estimators": 121,
    # num_leaves: 48
    n_jobs: -1,
    max_depth": 17,
    min_samples_leaf": 11,
    min_samples_split": 9,
    n_estimators": 198
  model_dir: "./train_model/glove/roneneldan/TinyStories/random_forest"
  dataset_dir: "./data.glove/roneneldan/TinyStories"
  tune: false
  #embedding_type: tree
  #dataset_column: 'python'



run_model:
  model_dir: "train_model/glove/roneneldan/TinyStories"
  model_name: "ardt_model.pkl"
  max_length: 100
